"""added columns for task status and priorities.

Revision ID: 48becdc54fae
Revises: a121bdc04258
Create Date: 2025-02-13 19:38:42.213395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48becdc54fae'
down_revision: Union[str, None] = 'a121bdc04258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.Integer(), server_default='1', nullable=False))
    op.add_column('tasks', sa.Column('priority', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
