"""deleted a column from the table tasks and renamed another.

Revision ID: a121bdc04258
Revises: 2f07391bbc4f
Create Date: 2025-02-12 13:36:52.742011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a121bdc04258'
down_revision: Union[str, None] = '2f07391bbc4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('tasks', 'content')
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###
