"""added indices for indexing over is_deleted column, since it's gonna be used for filtering oftenly.

Revision ID: c3566e8a8380
Revises: 2b9aedb053e4
Create Date: 2025-02-14 17:14:13.581365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3566e8a8380'
down_revision: Union[str, None] = '2b9aedb053e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_tasks_is_deleted', 'tasks', ['is_deleted'], unique=False)
    op.create_index('idx_users_is_deleted', 'users', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_is_deleted', table_name='users')
    op.drop_index('idx_tasks_is_deleted', table_name='tasks')
    # ### end Alembic commands ###
