"""added columns for soft-deleting tasks.

Revision ID: c679e8d67eaa
Revises: 48becdc54fae
Create Date: 2025-02-14 16:22:46.715569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c679e8d67eaa'
down_revision: Union[str, None] = '48becdc54fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('tasks', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deleted_at')
    op.drop_column('tasks', 'is_deleted')
    # ### end Alembic commands ###
