"""added a  column of modified at for tracking last modification date.

Revision ID: efe2156fd3d0
Revises: c679e8d67eaa
Create Date: 2025-02-14 17:00:03.176359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe2156fd3d0'
down_revision: Union[str, None] = 'c679e8d67eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('last_modified_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'last_modified_at')
    # ### end Alembic commands ###
